### ISSUE TITLE
Create a default configuration file

### ISSUE THREAD

**Issue by bevilla** [potierv/gameoftrust#5]
A QoL request, but having to `cp config.yml.template config.yml` is a bit unconvenient when cloning the project for the first time. And, as the project grows, it will be annoying to tell contributors "hey, I updated the config template, please update yours to add the new values".

What about having a versioned default config (let's call it default.yml), and a user config which is git ignored (user.yml) ?
The program can first start loading default.yml (which will contain all mandatory data set with default values), and then override the config with values from default.yml (if the file exists).

Example:
```
# default.yml
# you can edit the default values by creating a user.yml file

map:
  width: 50
  height: 20
gui: True
...
```
```
# user.yml

gui: False
...
```
```
# result after data loading

map:
  width: 50
  height: 20
gui: False
...
```
